import com.fernandes.drools.poc.domain.OrderRequest;
import com.fernandes.drools.poc.domain.SumOfOrders;

rule "Discount for CARD payment above 10000"
    when
        $orderFlow : OrderRequest($orderId: orderId,$paymentType: paymentType, $totalPrice: totalPrice, $discount: discount)
        not OrderRequest(totalPrice < $totalPrice)
    then
        System.out.println("orders: "+$paymentType+" :: "+$totalPrice);
        retract($orderFlow)
end;